#!/usr/bin/env python3
"""
UpdateCascade Static Verification & Governance Suite
Validates AST syntax, pure UTF-8 without BOM, author identity,
absence of AI attribution trailers, and launcher script templates.
"""

import os
import re
import sys
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

def test_no_utf8_bom():
    """Verify all text and script files do not contain UTF-8 BOM."""
    print("[TEST] Checking for absence of UTF-8 BOM...")
    extensions = {".ps1", ".py", ".md", ".txt", ".json", ".cmd", ".vbs", ".yml"}
    failed = []
    for root, _, files in os.walk(REPO_ROOT):
        if ".git" in root:
            continue
        for file in files:
            path = Path(root) / file
            if path.suffix.lower() in extensions or file == "cascade":
                with open(path, "rb") as f:
                    header = f.read(3)
                    if header == b"\xef\xbb\xbf":
                        failed.append(str(path))
    if failed:
        print(f"FAILED: Found UTF-8 BOM in {len(failed)} file(s): {failed}")
        sys.exit(1)
    print("  PASSED: Zero files contain UTF-8 BOM.")

def test_author_identity():
    """Verify canonical author identity in scripts and metadata."""
    print("[TEST] Checking canonical author identity...")
    cascade_ps1 = REPO_ROOT / "cascade.ps1"
    content = cascade_ps1.read_text(encoding="utf-8")
    assert "Matthew Bubb <matt@onyachamp.com>" in content, "Missing Matthew Bubb author identity"
    print("  PASSED: Author identity confirmed.")

def test_no_ai_trailers():
    """Ensure zero AI attribution trailers or disclaimers exist in code/docs."""
    print("[TEST] Checking for zero AI attribution trailers...")
    pattern = re.compile(r"(generated by (ai|claude|gemini|chatgpt|copilot|openai)|as an ai language model)", re.IGNORECASE)
    failed = []
    for root, _, files in os.walk(REPO_ROOT):
        if ".git" in root or "tests" in root:
            continue
        for file in files:
            path = Path(root) / file
            if path.suffix.lower() in {".ps1", ".py", ".md", ".cmd", ".vbs", ".yml"} or file == "cascade":
                text = path.read_text(encoding="utf-8", errors="ignore")
                if pattern.search(text):
                    failed.append(str(path))
    if failed:
        print(f"FAILED: Found AI attribution in: {failed}")
        sys.exit(1)
    print("  PASSED: Zero AI attribution trailers detected.")

def test_pure_ascii():
    """Verify cascade.ps1 and cascade are pure 7-bit ASCII."""
    print("[TEST] Checking pure ASCII compliance in cascade.ps1 and cascade...")
    for target in [REPO_ROOT / "cascade.ps1", REPO_ROOT / "cascade"]:
        data = target.read_bytes()
        non_ascii = [b for b in data if b > 127]
        assert len(non_ascii) == 0, f"Found {len(non_ascii)} non-ASCII byte(s) in {target.name}"
    print("  PASSED: 100% pure ASCII verified.")

def test_powershell_syntax():
    """Run PowerShell AST parser to ensure zero syntax or tokenizer errors."""
    print("[TEST] Parsing cascade.ps1 via PowerShell AST parser...")
    ps_cmd = (
        "$tokens = $null; $errs = $null; "
        "[System.Management.Automation.Language.Parser]::ParseFile("
        f"'{REPO_ROOT / 'cascade.ps1'}', [ref]$tokens, [ref]$errs); "
        "if ($errs) { $errs | ForEach-Object { $_.ToString() }; exit 1 } else { exit 0 }"
    )
    res = subprocess.run(["pwsh", "-NoProfile", "-Command", ps_cmd], capture_output=True, text=True, encoding="utf-8", errors="replace")
    if res.returncode != 0:
        print(f"FAILED: AST syntax errors found:\n{res.stdout}\n{res.stderr}")
        sys.exit(1)
    print("  PASSED: PowerShell AST parses with 0 errors.")

def test_raw_cascade_sync():
    """Verify extensionless cascade file is 100% byte-for-byte identical to cascade.ps1."""
    print("[TEST] Checking byte parity between cascade and cascade.ps1...")
    ps1_bytes = (REPO_ROOT / "cascade.ps1").read_bytes()
    raw_bytes = (REPO_ROOT / "cascade").read_bytes()
    assert ps1_bytes == raw_bytes, "cascade and cascade.ps1 differ!"
    print("  PASSED: Byte parity confirmed.")

def test_pester_suite():
    """Execute the full Pester test suite."""
    print("[TEST] Executing Pester test suite...")
    test_file = REPO_ROOT / "tests" / "UpdateCascade.Tests.ps1"
    res = subprocess.run(
        ["pwsh", "-NoProfile", "-Command", f"Invoke-Pester -Path '{test_file}' -Output Detailed"],
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace"
    )
    if "Failed: 0" not in res.stdout and "Tests Passed:" in res.stdout and "Failed: 0" in res.stdout:
        pass
    elif res.returncode != 0 or "[-] " in res.stdout:
        print(f"FAILED: Pester test failure:\n{res.stdout}")
        sys.exit(1)
    print("  PASSED: Pester test suite passed 100%.")

if __name__ == "__main__":
    print("\n=== Running UpdateCascade Verification Suite ===\n")
    test_no_utf8_bom()
    test_pure_ascii()
    test_author_identity()
    test_no_ai_trailers()
    test_powershell_syntax()
    test_raw_cascade_sync()
    test_pester_suite()
    print("\n=== ALL VERIFICATION TESTS PASSED SUCCESSFULLY! ===\n")
