# UpdateCascade Pester Unit and Integration Test Suite
# Tests state management, persistence registration, unregistration, launcher generation, runspace workers, and CLI parsing.

BeforeAll {
    $script:RepoRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
    $script:ScriptPath = Join-Path $script:RepoRoot 'cascade.ps1'
    
    $script:Tokens = $null
    $script:ParseErrors = $null
    $script:Ast = [System.Management.Automation.Language.Parser]::ParseFile(
        $script:ScriptPath,
        [ref]$script:Tokens,
        [ref]$script:ParseErrors
    )
}

Describe 'UpdateCascade Static Analysis & AST Syntax' {
    It 'Parses with zero syntax or tokenizer errors' {
        $script:ParseErrors.Count | Should -Be 0
    }

    It 'Contains required public parameters' {
        $paramBlock = $script:Ast.ParamBlock
        $paramNames = $paramBlock.Parameters.Name.VariablePath.UserPath
        $paramNames | Should -Contain 'Autonomous'
        $paramNames | Should -Contain 'MaxPasses'
        $paramNames | Should -Contain 'IncludeDrivers'
        $paramNames | Should -Contain 'RebootDelay'
        $paramNames | Should -Contain 'NoReboot'
        $paramNames | Should -Contain 'ScanOnly'
        $paramNames | Should -Contain 'ResumeFromRestart'
        $paramNames | Should -Contain 'Unregister'
        $paramNames | Should -Contain 'Status'
    }

    It 'Declares all persistence and core functions including New-CascadeRunspace' {
        $funcDefs = $script:Ast.FindAll({ $args[0] -is [System.Management.Automation.Language.FunctionDefinitionAst] }, $true)
        $funcNames = $funcDefs.Name

        $funcNames | Should -Contain 'Write-CascadeLog'
        $funcNames | Should -Contain 'Get-CascadeRuntimeContext'
        $funcNames | Should -Contain 'Save-CascadeSelfCopy'
        $funcNames | Should -Contain 'Get-CascadeState'
        $funcNames | Should -Contain 'Set-CascadeState'
        $funcNames | Should -Contain 'Clear-CascadeState'
        $funcNames | Should -Contain 'Register-CascadePersistence'
        $funcNames | Should -Contain 'Unregister-CascadePersistence'
        $funcNames | Should -Contain 'Invoke-CascadeReboot'
        $funcNames | Should -Contain 'Ensure-CascadeUpdateServices'
        $funcNames | Should -Contain 'Enable-MicrosoftUpdateCatalog'
        $funcNames | Should -Contain 'Get-CascadePendingUpdates'
        $funcNames | Should -Contain 'Get-CascadeDoSnapshot'
        $funcNames | Should -Contain 'Get-CascadeDoDiff'
        $funcNames | Should -Contain 'Install-CascadeUpdates'
        $funcNames | Should -Contain 'Test-CascadeSystemRebootPending'
        $funcNames | Should -Contain 'Start-AutonomousCascadeLoop'
        $funcNames | Should -Contain 'New-CascadeRunspace'
        $funcNames | Should -Contain 'Start-CascadeGui'
    }
}

Describe 'UpdateCascade Encoding & Governance' {
    It 'cascade.ps1 is pure UTF-8 without BOM' {
        $bytes = [System.IO.File]::ReadAllBytes($script:ScriptPath)
        $hasBom = ($bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF)
        $hasBom | Should -Be $false
    }

    It 'cascade (raw extensionless) exists and matches cascade.ps1' {
        $rawPath = Join-Path $script:RepoRoot 'cascade'
        Test-Path $rawPath | Should -Be $true
        $bytesPs1 = [System.IO.File]::ReadAllBytes($script:ScriptPath)
        $bytesRaw = [System.IO.File]::ReadAllBytes($rawPath)
        $bytesRaw.Length | Should -Be $bytesPs1.Length
    }

    It 'Carries Matthew Bubb author identity' {
        $content = [System.IO.File]::ReadAllText($script:ScriptPath)
        $content | Should -Match 'Matthew Bubb <matt@onyachamp\.com>'
    }

    It 'Contains no AI attribution trailers or disclaimers' {
        $content = [System.IO.File]::ReadAllText($script:ScriptPath)
        $content | Should -Not -Match '(?i)generated by (ai|claude|gemini|chatgpt|openai)'
        $content | Should -Not -Match '(?i)as an ai language model'
    }
}

Describe 'UpdateCascade State Management & Persistence Flow' {
    BeforeAll {
        $testDir = Join-Path ([System.IO.Path]::GetTempPath()) "UpdateCascadeTest_$([Guid]::NewGuid().ToString('N'))"
        New-Item -Path $testDir -ItemType Directory -Force | Out-Null
        $script:TestStateFile = Join-Path $testDir 'cascade_state.json'
    }

    AfterAll {
        if (Test-Path $testDir) {
            Remove-Item -Path $testDir -Recurse -Force -ErrorAction SilentlyContinue
        }
    }

    It 'Serializes and deserializes cascade state cleanly including Autonomous mode' {
        $stateObj = [PSCustomObject]@{
            Active         = $true
            Autonomous     = $true
            CurrentPass    = 2
            MaxPasses      = 5
            IncludeDrivers = $true
            TotalInstalled = 14
            UpdatedUtc     = (Get-Date).ToUniversalTime().ToString('o')
            MachineName    = $env:COMPUTERNAME
        }
        $json = ConvertTo-Json $stateObj -Compress
        [System.IO.File]::WriteAllText($script:TestStateFile, $json, [System.Text.Encoding]::UTF8)

        Test-Path $script:TestStateFile | Should -Be $true
        $read = ConvertFrom-Json ([System.IO.File]::ReadAllText($script:TestStateFile, [System.Text.Encoding]::UTF8))
        $read.Active | Should -Be $true
        $read.Autonomous | Should -Be $true
        $read.CurrentPass | Should -Be 2
        $read.MaxPasses | Should -Be 5
        $read.TotalInstalled | Should -Be 14
        $read.IncludeDrivers | Should -Be $true
    }

    It 'Cleans up state file on completion' {
        Remove-Item -Path $script:TestStateFile -Force -ErrorAction SilentlyContinue
        Test-Path $script:TestStateFile | Should -Be $false
    }
}

Describe 'UpdateCascade Architecture & Worker Isolation' {
    It 'Script contains New-CascadeRunspace definition that wires functions' {
        $content = [System.IO.File]::ReadAllText($script:ScriptPath)
        $content | Should -Match 'function New-CascadeRunspace'
        $content | Should -Match 'SessionStateFunctionEntry'
        $content | Should -Match 'Get-CascadePendingUpdates'
    }

    It 'Script contains P/Invoke shutdown privilege adjustment' {
        $content = [System.IO.File]::ReadAllText($script:ScriptPath)
        $content | Should -Match 'AdjustTokenPrivileges'
        $content | Should -Match 'SeShutdownPrivilege'
        $content | Should -Match 'EnableShutdownPrivilege'
    }

    It 'resume.cmd contains self-healing payload check' {
        $content = [System.IO.File]::ReadAllText($script:ScriptPath)
        $content | Should -Match 'RecoverPayload'
        $content | Should -Match 'DownloadFile'
    }

    It 'OOBE Setup CmdLine hook vector is implemented' {
        $content = [System.IO.File]::ReadAllText($script:ScriptPath)
        $content | Should -Match 'HKLM:\\SYSTEM\\Setup'
        $content | Should -Match 'UpdateCascade_CmdLine_Orig'
    }
}

Describe 'UpdateCascade CLI Invocation Verification' {
    It 'Returns status JSON when invoked with -Status' {
        $proc = Start-Process -FilePath "powershell.exe" -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File `"$script:ScriptPath`" -Status" -NoNewWindow -PassThru -RedirectStandardOutput (Join-Path $script:RepoRoot 'test_out.txt')
        $proc.WaitForExit(8000)
        $proc.ExitCode | Should -Be 0
        $out = Get-Content (Join-Path $script:RepoRoot 'test_out.txt') -Raw
        Remove-Item (Join-Path $script:RepoRoot 'test_out.txt') -Force -ErrorAction SilentlyContinue
        $json = ConvertFrom-Json $out
        $json | Should -Not -BeNullOrEmpty
    }

    It 'Handles -Unregister cleanly without unhandled exceptions' {
        $proc = Start-Process -FilePath "powershell.exe" -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File `"$script:ScriptPath`" -Unregister" -NoNewWindow -PassThru
        $proc.WaitForExit(10000)
        $proc.ExitCode | Should -Be 0
    }
}

Describe 'UpdateCascade WPF GUI & XAML Contract' {
    BeforeAll {
        Add-Type -AssemblyName PresentationFramework, PresentationCore, WindowsBase
        $content = [System.IO.File]::ReadAllText($script:ScriptPath)
        $startMarker = '$xaml = @"'
        $startIdx = $content.IndexOf($startMarker)
        $endIdx = $content.IndexOf('"@', $startIdx)
        $script:XamlText = $content.Substring($startIdx + $startMarker.Length, $endIdx - ($startIdx + $startMarker.Length)).Trim()
    }

    It 'Extracts valid XAML template from script' {
        $script:XamlText.Length | Should -BeGreaterThan 100
        $script:XamlText | Should -Match '^<Window'
    }

    It 'Does not contain invalid WPF attributes such as LetterSpacing' {
        $script:XamlText | Should -Not -Match 'LetterSpacing'
    }

    It 'Loads XAML via XamlReader and verifies window and all 27 bound controls are non-null' {
        $reader = [System.Xml.XmlReader]::Create([System.IO.StringReader]::new($script:XamlText))
        $window = [System.Windows.Markup.XamlReader]::Load($reader)
        $window | Should -Not -BeNullOrEmpty

        $expectedControls = @(
            'TxtPillStatus', 'PillStatus', 'PillSource', 'TxtPillSource', 'TxtBadgePass',
            'TxtStatusMessage', 'TxtSourceDetail', 'TxtTotalStats',
            'ProgCurrentStep', 'BannerCountdown', 'TxtCountdown', 'BtnRestartNow', 'BtnCancelCountdown',
            'LstUpdates', 'BtnSelectAll', 'BtnDeselectAll', 'TxtLogConsole', 'BtnClearLog',
            'BtnCopyLog', 'ChkIncludeDrivers', 'CmbMaxPasses', 'BtnStartCascade', 'BtnPauseCascade',
            'BtnScanOnly', 'BtnInstallSelected', 'BtnManualReboot', 'BtnUnregisterAll'
        )

        $expectedControls.Count | Should -Be 27

        foreach ($name in $expectedControls) {
            $ctl = $window.FindName($name)
            $ctl | Should -Not -BeNullOrEmpty -Because "Control '$name' must exist in XAML and be findable via FindName"
        }
    }

    It 'Contains zero modal MessageBox dialog calls ensuring pure 1-click execution' {
        $content = [System.IO.File]::ReadAllText($script:ScriptPath)
        $content | Should -Not -Match 'MessageBox'
    }

    It 'Contains zero modal Popup or Prompt dialog invocations' {
        $content = [System.IO.File]::ReadAllText($script:ScriptPath)
        $content | Should -Not -Match '(?i)WScript\.Shell.*Popup'
        $content | Should -Not -Match '(?i)\[Microsoft\.VisualBasic\.Interaction\]'
        $content | Should -Not -Match '(?i)Read-Host'
    }

    It 'Ensures all GUI button event handlers use inline status reporting ($fnSetStatus) without blocking modal dialogs' {
        $content = [System.IO.File]::ReadAllText($script:ScriptPath)
        # Check btnManualReboot
        $content | Should -Match '\$btnManualReboot\.Add_Click\(\{\s*& \$fnSetStatus "Initiating immediate system reboot\.\.\."'
        # Check btnUnregisterAll
        $content | Should -Match '\$btnUnregisterAll\.Add_Click\(\{\s*\$cnt = Unregister-CascadePersistence\s*& \$fnSetStatus "Successfully disarmed and cleaned'
        # Check btnInstallSelected with 0 updates
        $content | Should -Match '& \$fnSetStatus "No updates selected\.'
        # Check btnRestartNow
        $content | Should -Match '\$btnRestartNow\.Add_Click\(\{\s*& \$fnSetStatus "Initiating immediate system reboot\.\.\."'
        # Check btnScanOnly
        $content | Should -Match '\$btnScanOnly\.Add_Click\(\{\s*& \$fnSetStatus "Scanning for pending updates and drivers\.\.\."'
    }

    It 'Ensures manual installation completion reports status inline with REBOOT REQ or COMPLETED status pill' {
        $content = [System.IO.File]::ReadAllText($script:ScriptPath)
        $content | Should -Match 'REBOOT REQ'
        $content | Should -Match 'Manual install complete'
    }
}

Describe 'UpdateCascade Delivery Optimization & LAN Peering Indicators' {
    It 'Ensure-CascadeUpdateServices manages DoSvc and configures DODownloadMode' {
        $content = [System.IO.File]::ReadAllText($script:ScriptPath)
        $content | Should -Match "'DoSvc'"
        $content | Should -Match 'DODownloadMode'
    }

    It 'Declares Get-CascadeDoSnapshot and Get-CascadeDoDiff functions' {
        $funcDefs = $script:Ast.FindAll({ $args[0] -is [System.Management.Automation.Language.FunctionDefinitionAst] }, $true)
        $funcNames = $funcDefs.Name
        $funcNames | Should -Contain 'Get-CascadeDoSnapshot'
        $funcNames | Should -Contain 'Get-CascadeDoDiff'
    }

    It 'XAML interface contains dedicated PillSource and TxtSourceDetail indicators' {
        $content = [System.IO.File]::ReadAllText($script:ScriptPath)
        $content | Should -Match 'Name="PillSource"'
        $content | Should -Match 'Name="TxtPillSource"'
        $content | Should -Match 'Name="TxtSourceDetail"'
    }

    It 'Logs prominent LAN vs WAN source indicators' {
        $content = [System.IO.File]::ReadAllText($script:ScriptPath)
        $content | Should -Match '\[SOURCE: LAN PEER \(PREFERRED\)\]'
        $content | Should -Match '\[SOURCE: WAN CDN \(WARNING\)\]'
        $content | Should -Match '\[SOURCE: HYBRID \(LAN \+ WAN\)\]'
        $content | Should -Match '\[SOURCE: LOCAL CACHE\]'
    }
}




