# UpdateCascade Pester Unit and Integration Test Suite
# Tests state management, persistence registration, unregistration, launcher generation, and CLI parsing.

BeforeAll {
    $script:RepoRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
    $script:ScriptPath = Join-Path $script:RepoRoot 'cascade.ps1'
    
    $script:Tokens = $null
    $script:ParseErrors = $null
    $script:Ast = [System.Management.Automation.Language.Parser]::ParseFile(
        $script:ScriptPath,
        [ref]$script:Tokens,
        [ref]$script:ParseErrors
    )
}

Describe 'UpdateCascade Static Analysis & AST Syntax' {
    It 'Parses with zero syntax or tokenizer errors' {
        $script:ParseErrors.Count | Should -Be 0
    }

    It 'Contains required public parameters' {
        $paramBlock = $script:Ast.ParamBlock
        $paramNames = $paramBlock.Parameters.Name.VariablePath.UserPath
        $paramNames | Should -Contain 'Autonomous'
        $paramNames | Should -Contain 'MaxPasses'
        $paramNames | Should -Contain 'IncludeDrivers'
        $paramNames | Should -Contain 'RebootDelay'
        $paramNames | Should -Contain 'NoReboot'
        $paramNames | Should -Contain 'ScanOnly'
        $paramNames | Should -Contain 'ResumeFromRestart'
        $paramNames | Should -Contain 'Unregister'
        $paramNames | Should -Contain 'Status'
    }

    It 'Declares all 17 persistence and core functions' {
        $funcDefs = $script:Ast.FindAll({ $args[0] -is [System.Management.Automation.Language.FunctionDefinitionAst] }, $true)
        $funcNames = $funcDefs.Name

        $funcNames | Should -Contain 'Write-CascadeLog'
        $funcNames | Should -Contain 'Get-CascadeRuntimeContext'
        $funcNames | Should -Contain 'Save-CascadeSelfCopy'
        $funcNames | Should -Contain 'Get-CascadeState'
        $funcNames | Should -Contain 'Set-CascadeState'
        $funcNames | Should -Contain 'Clear-CascadeState'
        $funcNames | Should -Contain 'Register-CascadePersistence'
        $funcNames | Should -Contain 'Unregister-CascadePersistence'
        $funcNames | Should -Contain 'Invoke-CascadeReboot'
        $funcNames | Should -Contain 'Ensure-CascadeUpdateServices'
        $funcNames | Should -Contain 'Enable-MicrosoftUpdateCatalog'
        $funcNames | Should -Contain 'Get-CascadePendingUpdates'
        $funcNames | Should -Contain 'Install-CascadeUpdates'
        $funcNames | Should -Contain 'Test-CascadeSystemRebootPending'
        $funcNames | Should -Contain 'Start-AutonomousCascadeLoop'
        $funcNames | Should -Contain 'Start-CascadeGui'
    }
}

Describe 'UpdateCascade Encoding & Governance' {
    It 'cascade.ps1 is pure UTF-8 without BOM' {
        $bytes = [System.IO.File]::ReadAllBytes($script:ScriptPath)
        $hasBom = ($bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF)
        $hasBom | Should -Be $false
    }

    It 'cascade (raw extensionless) exists and matches cascade.ps1' {
        $rawPath = Join-Path $script:RepoRoot 'cascade'
        Test-Path $rawPath | Should -Be $true
        $bytesPs1 = [System.IO.File]::ReadAllBytes($script:ScriptPath)
        $bytesRaw = [System.IO.File]::ReadAllBytes($rawPath)
        $bytesRaw.Length | Should -Be $bytesPs1.Length
    }

    It 'Carries Matthew Bubb author identity' {
        $content = [System.IO.File]::ReadAllText($script:ScriptPath)
        $content | Should -Match 'Matthew Bubb <matt@onyachamp\.com>'
    }

    It 'Contains no AI attribution trailers or disclaimers' {
        $content = [System.IO.File]::ReadAllText($script:ScriptPath)
        $content | Should -Not -Match '(?i)generated by (ai|claude|gemini|chatgpt|openai)'
        $content | Should -Not -Match '(?i)as an ai language model'
    }
}

Describe 'UpdateCascade State Management & Persistence Flow' {
    BeforeAll {
        $testDir = Join-Path ([System.IO.Path]::GetTempPath()) "UpdateCascadeTest_$([Guid]::NewGuid().ToString('N'))"
        New-Item -Path $testDir -ItemType Directory -Force | Out-Null
        $script:TestStateFile = Join-Path $testDir 'cascade_state.json'
    }

    AfterAll {
        if (Test-Path $testDir) {
            Remove-Item -Path $testDir -Recurse -Force -ErrorAction SilentlyContinue
        }
    }

    It 'Serializes and deserializes cascade state cleanly' {
        $stateObj = [PSCustomObject]@{
            Active         = $true
            CurrentPass    = 2
            MaxPasses      = 5
            IncludeDrivers = $true
            TotalInstalled = 14
            UpdatedUtc     = (Get-Date).ToUniversalTime().ToString('o')
            MachineName    = $env:COMPUTERNAME
        }
        $json = ConvertTo-Json $stateObj -Compress
        [System.IO.File]::WriteAllText($script:TestStateFile, $json, [System.Text.Encoding]::UTF8)

        Test-Path $script:TestStateFile | Should -Be $true
        $read = ConvertFrom-Json ([System.IO.File]::ReadAllText($script:TestStateFile, [System.Text.Encoding]::UTF8))
        $read.Active | Should -Be $true
        $read.CurrentPass | Should -Be 2
        $read.MaxPasses | Should -Be 5
        $read.TotalInstalled | Should -Be 14
        $read.IncludeDrivers | Should -Be $true
    }

    It 'Cleans up state file on completion' {
        Remove-Item -Path $script:TestStateFile -Force -ErrorAction SilentlyContinue
        Test-Path $script:TestStateFile | Should -Be $false
    }
}

Describe 'UpdateCascade CLI Invocation Verification' {
    It 'Returns status JSON when invoked with -Status' {
        $proc = Start-Process -FilePath "powershell.exe" -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File `"$script:ScriptPath`" -Status" -NoNewWindow -PassThru -RedirectStandardOutput (Join-Path $script:RepoRoot 'test_out.txt')
        $proc.WaitForExit(8000)
        $proc.ExitCode | Should -Be 0
        $out = Get-Content (Join-Path $script:RepoRoot 'test_out.txt') -Raw
        Remove-Item (Join-Path $script:RepoRoot 'test_out.txt') -Force -ErrorAction SilentlyContinue
        $json = ConvertFrom-Json $out
        $json | Should -Not -BeNullOrEmpty
    }

    It 'Handles -Unregister cleanly without unhandled exceptions' {
        $proc = Start-Process -FilePath "powershell.exe" -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File `"$script:ScriptPath`" -Unregister" -NoNewWindow -PassThru
        $proc.WaitForExit(10000)
        $proc.ExitCode | Should -Be 0
    }
}
